baseURL = "https://gallant-dijkstra-175383.netlify.app"
canonifyURLs = true
languageCode = "en-us"
summarylength = 25
theme = "roxo"
title = "Vimal | AIML Portfolio"
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.nav]]
name = "Report"
url = "blog"
weight = 4
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 5
[params]
author = "StaticMania"
dateFormat = "26 FEB 1994"
description = "Roxo Hugo themes | Design Agency Template by StaticMania"
formspreeFormUrl = "https://formspree.io/f/xrgovlbd"
googleAnalitycsID = "Your ID"
logo = "images/AI-footer.gif"
[params.banner]
background_image = "images/backgrounds/AIML Portfolio.gif"
enable = true
heading = ""
primary_button = "See My Works"
primary_button_url = "portfolio"
secondary_button = "Connect with Me"
secondary_button_url = "contact"
tagline = ""
[params.call_to_action]
background_image = "images/backgrounds/cta-background.gif"
enable = true
primary_button = "Hire me"
primary_button_url = "contact"
secondary_button = "Not Convinced"
secondary_button_url = "portfolio"
title = "LET’S WORK TOGETHER"
[params.footer.contactInfo]
address = "ALUVA,KERALA"
email = "vimalranjeev9@gmail.com"
title = "Contact Info"
[params.footer.service]
description = "machine learning model and deep learrning model by obtaining dataset provided during the course, kaggle and UCI ML repository."
title = "I try to build:"
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Me"
url = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "LinkedIN"
url = "https://www.linkedin.com/in/vimal-ranjeev-258131158/"
[[params.footer.social.link]]
name = "GitHub"
url = "https://github.com/VIMALRANJEEV"
[[params.footer.social.link]]
name = "Kaggle"
url = "https://www.kaggle.com/vimalranjeev"
[params.navAction]
name = "Get in touch"
status = true
url = "contact"
[params.portfolio]
enable = true
subtitle = "Bulding and learning complex AI models since 2020"
title = "MY RECENT WORKS"
